const DISPLAY_REPORT = 'DISPLAY_REPORT'
const FETCH_REPORT = 'FETCH_REPORT'
const FETCH_REPORT_DONE = 'FETCH_REPORT_DONE'

const Types = {
    DISPLAY_REPORT,
    FETCH_REPORT,
    FETCH_REPORT_DONE
}

export default Types
export { DISPLAY_REPORT, FETCH_REPORT, FETCH_REPORT_DONE }
